// Code Generated by Sidekick is for learning and experimentation purposes only.

Cypress.Commands.overwrite('type', (originalFn, element, text, options) => {

  if (options && options.sensitive) {

    options.log = false

    Cypress.log({

      $el: element,

      name: 'type',

      message: '*'.repeat(String(text).length),

    })

  }
 
  return originalFn(element, text, options)

})
 
Cypress.Commands.add('login', (email, password) => {

cy.visit('/', {
  auth: {
    username: 'guest',
    password: 'welcome2qauto'
  }
})
 
  cy.contains('button', 'Sign In').click()
 
  cy.get('#signinEmail').should('be.visible').clear().type(email)

  cy.get('#signinPassword').should('be.visible').clear().type(password, { sensitive: true })
 
  cy.contains('button', 'Login').click()
 
  cy.url().should('include', '/panel/garage')

})

 